# Generated by Django 4.0 on 2022-04-08 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('num_tasks', models.PositiveIntegerField()),
                ('description', models.TextField(null=True)),
                ('num_stale', models.IntegerField(null=True)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StaleOwnerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.TextField()),
                ('old_owner', models.TextField()),
                ('new_owner', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch_processing.batchjob')),
            ],
        ),
    ]
