# Generated by Django 4.0.1 on 2022-12-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_api_key', '0004_prefix_hashed_key'),
        ('api', '0168_erc721token_api_erc721t_approve_971137_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicAPIKeyAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_path', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_framework_api_key.apikey')),
            ],
        ),
    ]
