# Generated by Django 4.0 on 2022-03-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='max_per_mint',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostedcollection',
            name='max_per_premint',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hostedcollection',
            name='max_supply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedcollection',
            name='mint_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostedcollection',
            name='premint_price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
