# Generated by Django 4.0 on 2022-03-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0002_hostedcollection_max_per_mint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenlistedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launchpad.hostedcollection')),
            ],
            options={
                'unique_together': {('collection', 'address')},
            },
        ),
    ]
