# Generated by Django 4.0 on 2022-03-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0003_greenlistedaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='mint_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostedcollection',
            name='premint_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
