# Generated by Django 4.0 on 2022-03-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0004_hostedcollection_mint_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='premint',
            field=models.BooleanField(default=False),
        ),
    ]
