# Generated by Django 4.0 on 2022-03-08 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0006_hostedcollection_metadata_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedmetadata',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
