# Generated by Django 4.0 on 2022-03-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0007_hostedmetadata_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='base_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
