# Generated by Django 4.0 on 2022-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0008_hostedcollection_base_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='base_uri_file_extension',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hostedcollection',
            name='base_uri_token_id',
            field=models.BooleanField(default=True),
        ),
    ]
