# Generated by Django 4.0 on 2022-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0009_hostedcollection_base_uri_file_extension_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedcollection',
            name='address',
            field=models.TextField(null=True, unique=True),
        ),
    ]
