# Generated by Django 4.0 on 2022-03-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0010_alter_hostedcollection_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='src_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
