# Generated by Django 4.0.1 on 2022-07-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0011_hostedcollection_src_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='reserve_tokens',
            field=models.BooleanField(default=False),
        ),
    ]
