# Generated by Django 4.0.1 on 2022-08-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0012_hostedcollection_reserve_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedcollection',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
