# Generated by Django 4.0.1 on 2022-08-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchpad', '0013_hostedcollection_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedcollection',
            name='address',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='hostedcollection',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
